FROM composer as composer-dev
WORKDIR /app
COPY ./composer.json ./
COPY ./composer.lock ./
RUN composer install --no-scripts --ignore-platform-reqs

FROM php:7.4-fpm-alpine as ci-dev
RUN apk add --no-cache \
    $PHPIZE_DEPS \
    sqlite-dev && \
    docker-php-ext-install bcmath && \
    docker-php-ext-enable bcmath && \
    docker-php-ext-install pdo pdo_sqlite && \
    docker-php-ext-enable pdo pdo_sqlite && \
    docker-php-ext-install opcache && \
    docker-php-ext-enable opcache && \
    rm -rf /tmp/pear

RUN  mkdir -p /var/www/html/var/log/
COPY ./docker/php/php.ini /usr/local/etc/php/php.ini
COPY ./ /var/www/html
COPY --from=composer-dev /app/vendor /var/www/html/vendor
RUN chmod 777 -R /var/www/html
RUN chown www-data:www-data /var/www/html/data/task.sqlite
