FROM php:7.4-fpm-alpine

RUN apk add --no-cache $PHPIZE_DEPS && \
    docker-php-ext-install bcmath && \
    docker-php-ext-enable bcmath && \
    docker-php-ext-install pdo pdo_mysql && \
    docker-php-ext-enable pdo pdo_mysql && \
    docker-php-ext-install opcache && \
    docker-php-ext-enable opcache && \
    pecl install -o -f redis && \
    rm -rf /tmp/pear && \
    echo "extension=redis.so" > /usr/local/etc/php/conf.d/redis.ini

RUN  mkdir -p /var/www/html/var/log/

COPY ./docker/php/php.ini /usr/local/etc/php/php.ini
COPY ./docker/php/php-fpm-pool.conf /etc/php7/php-fpm.d/www.conf

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer creates=/usr/local/bin/composer warn=no