security:
    providers:
        users:
            entity:
                class: 'App\Infrastructure\Entity\User'
                property: 'email'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: /
            anonymous: lazy
            logout: ~
            guard:
                authenticators:
                   - App\Infrastructure\Security\GoogleAuthenticator

    access_control:
      - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
