version: '3'

services:
  task_manager_purple_clouds_php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile-dev
    volumes:
      - .:/var/www/html
    networks: ["purple_clouds_network_internal"]

  task_manager_purple_clouds_nginx:
    image: nginx:latest
    ports:
      - "8002:8002"
    depends_on:
      - task_manager_purple_clouds_php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: ["purple_clouds_network_internal"]

networks:
  purple_clouds_network_internal: {"external": {"name": "purple_clouds_network_internal"}}