# Application frontend
homepage:
    path: /
    controller: App\Controller\FrontendController\HomepageController::homepage

app_logout:
    path: /logout
    methods: ['GET']

app_tasks:
    path: /tasks
    controller: App\Controller\FrontendController\TaskController::show
    methods: ['GET']

#Google OAuth2 routes
connect_google_start:
    path: /connect/google
    controller: App\Controller\GoogleController::connect

connect_google_check:
    path: /connect/google/check
    controller: App\Controller\GoogleController::connectCheck

# Users endpoints
user_promote:
    path: /api/users/{userId}/promote
    methods: ['GET']
    controller: App\Controller\ApiController\UserController::promote

# Tasks endpoints
task_create:
    path: /api/tasks
    methods: ['POST']
    controller: App\Controller\ApiController\TaskController::create

# Goal endpoints
goal_create:
    path: /api/goals
    methods: ['POST']
    controller: App\Controller\ApiController\GoalController::create

goal_find_by_id:
    path: /api/goals/{goalIdentifier}
    methods: ['GET']
    controller: App\Controller\ApiController\GoalController::find

goal_find_all:
    path: /api/goals
    methods: ['GET']
    controller: App\Controller\ApiController\GoalController::findAll